/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authAuthRouteImport } from './routes/(auth)/auth'
import { Route as appAppRouteImport } from './routes/(app)/app'
import { Route as authAuthSignUpRouteImport } from './routes/(auth)/auth/sign-up'
import { Route as authAuthSignInRouteImport } from './routes/(auth)/auth/sign-in'
import { Route as appAppGamesIndexRouteImport } from './routes/(app)/app/games/index'
import { Route as appAppAnalyzeIndexRouteImport } from './routes/(app)/app/analyze/index'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthRoute = authAuthRouteImport.update({
  id: '/(auth)/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const appAppRoute = appAppRouteImport.update({
  id: '/(app)/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const authAuthSignUpRoute = authAuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => authAuthRoute,
} as any)
const authAuthSignInRoute = authAuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => authAuthRoute,
} as any)
const appAppGamesIndexRoute = appAppGamesIndexRouteImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => appAppRoute,
} as any)
const appAppAnalyzeIndexRoute = appAppAnalyzeIndexRouteImport.update({
  id: '/analyze/',
  path: '/analyze/',
  getParentRoute: () => appAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof appAppRouteWithChildren
  '/auth': typeof authAuthRouteWithChildren
  '/auth/sign-in': typeof authAuthSignInRoute
  '/auth/sign-up': typeof authAuthSignUpRoute
  '/app/analyze/': typeof appAppAnalyzeIndexRoute
  '/app/games/': typeof appAppGamesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/app': typeof appAppRouteWithChildren
  '/auth': typeof authAuthRouteWithChildren
  '/auth/sign-in': typeof authAuthSignInRoute
  '/auth/sign-up': typeof authAuthSignUpRoute
  '/app/analyze': typeof appAppAnalyzeIndexRoute
  '/app/games': typeof appAppGamesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/(app)/app': typeof appAppRouteWithChildren
  '/(auth)/auth': typeof authAuthRouteWithChildren
  '/(auth)/auth/sign-in': typeof authAuthSignInRoute
  '/(auth)/auth/sign-up': typeof authAuthSignUpRoute
  '/(app)/app/analyze/': typeof appAppAnalyzeIndexRoute
  '/(app)/app/games/': typeof appAppGamesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app/analyze/'
    | '/app/games/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/app'
    | '/auth'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/app/analyze'
    | '/app/games'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/(app)/app'
    | '/(auth)/auth'
    | '/(auth)/auth/sign-in'
    | '/(auth)/auth/sign-up'
    | '/(app)/app/analyze/'
    | '/(app)/app/games/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  appAppRoute: typeof appAppRouteWithChildren
  authAuthRoute: typeof authAuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth': {
      id: '/(auth)/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof authAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/app': {
      id: '/(app)/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof appAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/auth/sign-up': {
      id: '/(auth)/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof authAuthSignUpRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(auth)/auth/sign-in': {
      id: '/(auth)/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof authAuthSignInRouteImport
      parentRoute: typeof authAuthRoute
    }
    '/(app)/app/games/': {
      id: '/(app)/app/games/'
      path: '/games'
      fullPath: '/app/games/'
      preLoaderRoute: typeof appAppGamesIndexRouteImport
      parentRoute: typeof appAppRoute
    }
    '/(app)/app/analyze/': {
      id: '/(app)/app/analyze/'
      path: '/analyze'
      fullPath: '/app/analyze/'
      preLoaderRoute: typeof appAppAnalyzeIndexRouteImport
      parentRoute: typeof appAppRoute
    }
  }
}

interface appAppRouteChildren {
  appAppAnalyzeIndexRoute: typeof appAppAnalyzeIndexRoute
  appAppGamesIndexRoute: typeof appAppGamesIndexRoute
}

const appAppRouteChildren: appAppRouteChildren = {
  appAppAnalyzeIndexRoute: appAppAnalyzeIndexRoute,
  appAppGamesIndexRoute: appAppGamesIndexRoute,
}

const appAppRouteWithChildren =
  appAppRoute._addFileChildren(appAppRouteChildren)

interface authAuthRouteChildren {
  authAuthSignInRoute: typeof authAuthSignInRoute
  authAuthSignUpRoute: typeof authAuthSignUpRoute
}

const authAuthRouteChildren: authAuthRouteChildren = {
  authAuthSignInRoute: authAuthSignInRoute,
  authAuthSignUpRoute: authAuthSignUpRoute,
}

const authAuthRouteWithChildren = authAuthRoute._addFileChildren(
  authAuthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  appAppRoute: appAppRouteWithChildren,
  authAuthRoute: authAuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
